name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  # dusk-tests:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   services:
  #     mysql:
  #       image: mysql:8
  #       env:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_test
  #       ports:
  #         - 3306:3306
  #       options: >-
  #         --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
  #         --health-interval=10s
  #         --health-timeout=5s
  #         --health-retries=5
  #   steps:
  #     # 1. Checkout Repository
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     # 2. Setup PHP Environment
  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: '8.2'
  #         extensions: mbstring, bcmath, openssl, pdo_mysql
  #         coverage: none

  #     # 3. Install Dependencies
  #     - name: Install dependencies
  #       run: composer install --no-progress --prefer-dist --optimize-autoloader

  #     # 4. Create .env file
  #     - name: Create .env file
  #       run: |
  #         cp .env.example .env
  #         php artisan key:generate
  #         echo "DB_CONNECTION=mysql" >> .env
  #         echo "DB_HOST=127.0.0.1" >> .env
  #         echo "DB_PORT=3306" >> .env
  #         echo "DB_DATABASE=laravel_test" >> .env
  #         echo "DB_USERNAME=root" >> .env
  #         echo "DB_PASSWORD=root" >> .env

  #     # 5. Run Migrations with Seed
  #     - name: Run migrations
  #       run: php artisan migrate:fresh --seed

  #     # 6. Install Chrome and ChromeDriver
  #     - name: Install Google Chrome
  #       run: sudo apt-get install -y google-chrome-stable

  #     - name: Install ChromeDriver
  #       run: php artisan dusk:chrome-driver --detect

  #     # 7. Run Laravel Dusk Tests
  #     # - name: Run Laravel Dusk Tests
  #     #   env:
  #     #     APP_URL: http://127.0.0.1:8000
  #     #   run: php artisan serve & sleep 5 && php artisan dusk

  #     # # 8. Upload Screenshots on Failure
  #     # - name: Upload screenshots
  #     #   if: failure()
  #     #   uses: actions/upload-artifact@v3
  #     #   with:
  #     #     name: dusk-screenshots
  #     #     path: tests/Browser/screenshots

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # 2. Deploy Files via FTP
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 103.139.193.151
          username: ftp-divops
          password: pass1234
